In [1]:
import pandas as pd;

In [2]:
from geopy.geocoders import Nominatim

In [3]:

# initialize Nominatim API 
geolocator = Nominatim(user_agent="geoapiExercises")

In [59]:
def getCounty(data, lat_column, lon_column):
    counties =[]
    for lat, lon in zip(data[lat_column], data[lon_column]):
        location = geolocator.reverse(str(lat)+","+str(lon))
        add = location.raw['address']
        counties.append(add['county'])
    
    data['county_calc'] = counties;

#location = geolocator.reverse(Latitude+","+Longitude)
#add = location.raw['address']
#print(add['county'])

In [73]:
df = pd.read_csv("harvey_highwater_incidents_RECENT.csv")
rf = pd.read_csv("Rainfall-V5.csv")

In [95]:
# Latitude & Longitude input
Latitude = df['LATITUDE_IB_CW']
Longitude = df['LONGITUDE_IB_CW']

data = pd.DataFrame({'lat': Latitude, 'lon' : Longitude})

In [96]:
getCounty(data, 'lat', 'lon')
data.shape
#df['LONGITUDE_IB_CW'].head

(468, 3)

In [97]:
data['county_calc'].unique()

array(['Harris County', 'Waller County', 'Fort Bend County',
       'Brazoria County', 'Montgomery County', 'Galveston County',
       'Austin County', 'Chambers County'], dtype=object)

In [98]:
df['county_calc'] = data['county_calc']

In [99]:
df.to_csv("Incidents-V4.csv", index=False, header=True)

In [63]:
Latitude = rf['LAT']
Longitude = rf['LON']

data = pd.DataFrame({'lat': Latitude, 'lon': Longitude})

In [64]:
getCounty(data, 'lat', 'lon')

TypeError: 'tuple' object is not callable

In [65]:
data.shape

(307, 3)

In [67]:
data['county_calc'].unique()

array(['Harris County', 'Fort Bend County', 'Galveston County',
       'Chambers County', 'Brazoria County', 'Liberty County',
       'Hardin County', 'Waller County', 'Austin County',
       'Montgomery County', 'Wharton County', 'Jefferson County',
       'Grimes County', 'Washington County'], dtype=object)

In [74]:
rf['County'] = data['county_calc']

In [87]:
#delete rows with entries for any other counties other than the 8

# Get names of indexes for which column has a differnt county value
indexNames = rf[rf['County'] ==  'Washington County'].index
indexNames

Int64Index([289], dtype='int64')

In [88]:
# Delete these row indexes from dataFrame
rf.drop(indexNames , inplace=True)

In [89]:
rf.shape

(293, 16)

In [90]:
rf.to_csv("Rainfall-V6.csv", index=False, header=True)

In [93]:
rf.drop(columns='Unnamed: 0')

,LAT,LON,25-Aug,26-Aug,27-Aug,28-Aug,29-Aug,30-Aug,31-Aug,1-Sep,Totals,Sum,IsSum_Total_Same?,elev_meters,County
0,29.550000,-95.080000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.12,0.00,0,-0.45,Harris County
1,29.800000,-95.770000,NaN,NaN,NaN,NaN,5.55,NaN,NaN,NaN,5.55,5.55,1,41.13,Harris County
2,29.790000,-95.620000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.20,0.00,0,26.93,Harris County
3,29.760000,-95.650000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.30,0.00,0,26.98,Fort Bend County
4,29.790908,-95.623570,0.88,9.12,17.08,5.04,1.32,0.00,0.0,NaN,33.44,33.44,1,27.84,Harris County
5,29.790000,-95.620000,NaN,NaN,NaN,NaN,NaN,0.23,NaN,NaN,0.23,0.23,1,26.93,Harris County
6,29.412200,-95.178700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.94,0.00,0,9.72,Galveston County
7,29.780000,-94.660000,0.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.56,0.56,1,6.10,Chambers County
8,29.752150,-94.673300,1.22,4.85,11.26,13.22,10.71,0.20,0.0,NaN,41.46,41.46,1,4.57,Chambers County
9,29.140000,-95.290000,0.33,8.05,3.77,2.37,6.37,0.80,0.0,NaN,21.69,21.69,1,3.05,Brazoria County
10,29.110000,-95.460000,2.02,5.61,2.34,2.45,5.91,0.16,NaN,NaN,18.49,18.49,1,7.17,Brazoria County
11,29.683502,-95.183473,1.00,11.52,15.88,10.12,4.84,0.00,0.0,NaN,43.36,43.36,1,8.93,Harris County
12,29.633755,-95.114485,1.00,8.36,18.60,9.76,4.56,0.00,0.0,NaN,42.28,42.28,1,4.25,Harris County
13,29.564191,-95.070795,1.68,5.52,20.68,10.12,3.52,0.04,0.0,NaN,41.56,41.56,1,-0.37,Harris County
14,29.769860,-95.646848,1.20,8.92,17.16,7.4,1.80,0.00,0.0,NaN,36.48,36.48,1,26.63,Fort Bend County
15,30.164440,-94.642780,0.27,3.19,11.97,7.32,8.82,1.89,0.0,NaN,33.46,33.46,1,19.19,Liberty County
17,29.770000,-95.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.90,0.00,0,1.13,Harris County
18,29.740000,-94.970000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.72,0.00,0,9.27,Harris County
19,29.591725,-95.222089,1.64,13.52,13.40,8.28,3.16,0.00,0.0,NaN,40.00,40.00,1,9.08,Harris County
20,29.831211,-95.687108,0.84,8.72,16.28,5.16,1.48,0.00,0.0,NaN,32.48,32.48,1,34.96,Harris County
21,29.875125,-95.769477,0.76,9.24,17.64,4,1.32,0.00,0.0,NaN,32.96,32.96,1,45.01,Harris County
22,29.676389,-95.243610,1.16,13.64,15.72,9.64,4.72,0.00,0.0,NaN,44.88,44.88,1,7.70,Harris County
23,29.656295,-95.228933,1.48,14.40,14.84,9.24,4.64,0.00,0.0,NaN,44.60,44.60,1,8.02,Harris County
24,29.651497,-95.076001,1.04,5.16,18.08,9.72,4.96,0.00,0.0,NaN,38.96,38.96,1,5.91,Harris County
25,30.237906,-95.839529,0.28,12.36,13.60,1.64,0.48,0.00,0.0,NaN,28.36,28.36,1,80.74,Waller County
26,29.703910,-95.566081,0.92,7.96,13.24,7.44,1.36,0.00,0.0,NaN,30.92,30.92,1,21.01,Harris County
27,29.709284,-95.582500,1.28,10.20,15.56,5.96,0.96,0.00,0.0,NaN,33.96,33.96,1,22.90,Harris County
28,29.695066,-95.556599,1.24,10.08,14.84,7.52,1.28,0.00,0.0,NaN,34.96,34.96,1,20.60,Harris County
29,29.672371,-95.527994,1.48,9.36,15.32,7.48,1.56,0.00,0.0,NaN,35.20,35.20,1,18.68,Harris County
30,29.722625,-95.305332,0.96,8.48,14.28,8.8,3.20,0.00,0.0,NaN,35.72,35.72,1,4.92,Harris County
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,29.565371,-95.053834,2.04,4.88,18.44,11.44,4.16,0.00,0.0,NaN,40.96,40.96,1,0.09,Harris County
274,29.619923,-95.021669,1.48,6.08,18.84,10.64,4.76,0.00,0.0,NaN,41.80,41.80,1,-0.44,Harris County
275,29.400000,-94.950000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.84,0.00,0,2.09,Galveston County
276,29.420000,-94.890000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.97,0.00,0,1.93,Galveston County
277,29.400000,-95.020000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.00,0.00,0,6.38,Galveston County
278,30.120000,-95.470000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.50,0.00,0,34.78,Montgomery County
281,30.152994,-95.863216,0.32,11.96,12.16,1.68,0.48,0.00,0.0,NaN,26.60,26.60,1,74.71,Waller County
282,30.060000,-95.620000,NaN,NaN,NaN,8.92,NaN,NaN,NaN,NaN,8.92,8.92,1,48.44,Harris County
283,29.583903,-95.187552,2.20,12.48,13.48,10.4,3.44,0.00,0.0,NaN,42.00,42.00,1,7.73,Harris County
284,29.827990,-94.669630,1.34,5.47,11.81,11.81,10.16,1.18,0.0,NaN,41.77,41.77,1,2.12,Chambers County
285,29.694493,-95.216140,1.04,13.16,15.72,8.8,3.96,0.00,0.0,NaN,42.68,42.68,1,6.50,Harris County
286,29.883128,-95.467416,0.72,6.60,17.56,6.36,2.24,0.00,0.0,NaN,33.48,33.48,1,22.98,Harris County
287,29.868133,-95.469200,0.76,6.64,17.92,6.72,2.32,0.00,0.0,NaN,34.36,34.36,1,18.42,Harris County
288,30.178866,-95.809912,0.32,12.80,12.20,2.04,0.68,0.00,0.0,NaN,28.04,28.04,1,67.04,Waller County
290,29.550000,-95.140000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.30,0.00,0,9.26,Harris County
291,29.500000,-95.120000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.20,0.00,0,5.86,Galveston County
292,29.140000,-95.630000,2.72,4.75,NaN,2.69,NaN,NaN,NaN,NaN,10.16,10.16,1,8.68,Brazoria County
294,29.803438,-95.429368,0.68,4.80,14.36,6.96,2.24,0.00,0.0,NaN,29.04,29.04,1,16.93,Harris County
295,29.877297,-95.524522,0.72,5.96,16.00,5.2,1.56,0.00,0.0,NaN,29.44,29.44,1,28.03,Harris County
296,29.917687,-95.584556,0.64,6.12,14.88,4.8,1.24,0.00,0.0,NaN,27.68,27.68,1,33.50,Harris County
297,29.887358,-95.556185,0.68,6.36,15.64,5.68,1.68,0.00,0.0,NaN,30.04,30.04,1,29.61,Harris County
298,29.840915,-95.458339,0.76,6.60,17.36,6.28,2.16,0.00,0.0,NaN,33.16,33.16,1,19.52,Harris County
299,29.846237,-95.460193,0.76,6.72,17.68,5.08,1.64,0.00,0.0,NaN,31.88,31.88,1,21.05,Harris County
300,30.030570,-94.595000,0.43,4.21,17.05,8.35,8.77,1.54,0.0,NaN,40.35,40.35,1,17.09,Liberty County
301,30.420000,-95.490000,NaN,NaN,5.00,NaN,NaN,NaN,NaN,NaN,5.00,5.00,1,118.71,Montgomery County
302,30.105339,-95.546382,0.28,6.48,15.04,3.72,1.76,0.00,0.0,NaN,27.28,27.28,1,38.94,Harris County
303,30.063023,-95.620855,0.28,6.00,14.92,3.8,1.60,0.00,0.0,NaN,26.60,26.60,1,45.14,Harris County
304,29.650747,-95.110027,1.08,7.72,19.68,10.52,4.68,0.00,0.0,NaN,43.68,43.68,1,6.80,Harris County
305,29.650230,-95.486700,1.80,7.92,14.32,7.88,1.96,0.00,0.0,NaN,33.88,33.88,1,16.57,Harris County
306,29.664477,-95.460008,1.60,8.12,13.56,7.28,1.92,0.00,0.0,NaN,32.48,32.48,1,12.95,Harris County

In [94]:
rf.to_csv("Rainfall-V7.csv", index=False, header = True)

In [102]:
df = df.rename(columns={'county_calc':'County'})
print("Rainfall - ",rf.columns)
print("Incidents- ",df.columns)

Rainfall -  Index(['Unnamed: 0', 'LAT', 'LON', '25-Aug', '26-Aug', '27-Aug', '28-Aug',
       '29-Aug', '30-Aug', '31-Aug', '1-Sep', 'Totals', 'Sum',
       'IsSum_Total_Same?', 'elev_meters', 'County'],
      dtype='object')
Incidents-  Index(['ROADWAY_NAME', 'LATITUDE_IB_CW', 'LATITUDE_OB_CCW', 'LONGITUDE_IB_CW',
       'LONGITUDE_OB_CCW', 'COUNTY_NAME', 'TOTAL_MINUTES', 'ENTER_DATE',
       'ENTER_TIME', 'CLEAR_DATE', 'CLEAR_TIME', 'elev_meters', 'County'],
      dtype='object')

In [103]:
right_merge = pd.merge(rf, df, on='County', how='right')

In [106]:
right_merge.shape

(68928, 28)

In [108]:
right_merge.columns

Index(['Unnamed: 0', 'LAT', 'LON', '25-Aug', '26-Aug', '27-Aug', '28-Aug',
       '29-Aug', '30-Aug', '31-Aug', '1-Sep', 'Totals', 'Sum',
       'IsSum_Total_Same?', 'elev_meters_x', 'County', 'ROADWAY_NAME',
       'LATITUDE_IB_CW', 'LATITUDE_OB_CCW', 'LONGITUDE_IB_CW',
       'LONGITUDE_OB_CCW', 'COUNTY_NAME', 'TOTAL_MINUTES', 'ENTER_DATE',
       'ENTER_TIME', 'CLEAR_DATE', 'CLEAR_TIME', 'elev_meters_y'],
      dtype='object')

In [114]:
right_merge.describe()

,Unnamed: 0,LAT,LON,25-Aug,26-Aug,27-Aug,29-Aug,30-Aug,31-Aug,1-Sep,Totals,Sum,IsSum_Total_Same?,elev_meters_x,LATITUDE_IB_CW,LATITUDE_OB_CCW,LONGITUDE_IB_CW,LONGITUDE_OB_CCW,TOTAL_MINUTES,elev_meters_y
count,68928.000000,68928.000000,68928.000000,44940.000000,43296.000000,42824.000000,45244.000000,43892.000000,41799.000000,0.0,68928.000000,68928.000000,68928.000000,68928.000000,68928.000000,68928.000000,68928.000000,68928.000000,68928.000000,68928.000000
mean,146.458623,29.789489,-95.360739,0.835651,7.542662,15.922065,3.138468,0.092269,0.000463,NaN,29.737328,22.152641,0.810338,18.623100,29.784479,29.784460,-95.386724,-95.386751,3039.842111,18.749361
std,85.678387,0.157017,0.222964,0.493761,2.558003,2.565800,1.896357,0.528609,0.019700,NaN,13.215356,16.015701,0.392036,13.815052,0.141109,0.141168,0.178770,0.178812,1810.856936,12.374981
min,0.000000,29.110000,-96.040000,0.000000,0.350000,2.340000,0.200000,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,-0.460000,29.078550,29.078550,-96.152700,-96.152700,-1.000000,-0.120000
25%,74.000000,29.674494,-95.527994,0.480000,6.000000,14.360000,1.640000,0.000000,0.000000,NaN,28.640000,1.680000,1.000000,8.220000,29.683900,29.683800,-95.517700,-95.517600,1705.000000,10.300000
50%,144.000000,29.782684,-95.349320,0.800000,7.360000,16.000000,2.640000,0.000000,0.000000,NaN,32.960000,30.040000,1.000000,15.740000,29.774300,29.774100,-95.381200,-95.381300,3315.000000,16.210000
75%,215.000000,29.900000,-95.180000,1.080000,9.200000,17.560000,4.200000,0.000000,0.000000,NaN,38.200000,34.560000,1.000000,25.250000,29.883110,29.883110,-95.262200,-95.262400,4076.000000,23.040000
max,306.000000,30.420000,-94.388900,3.620000,14.400000,27.360000,19.170000,5.420000,0.840000,NaN,56.000000,48.200000,1.000000,118.710000,30.421000,30.421000,-94.388372,-94.388372,9834.000000,108.650000

In [115]:
right_merge = right_merge.drop(columns={'Unnamed: 0', '1-Sep'})

In [116]:
right_merge.describe()

,LAT,LON,25-Aug,26-Aug,27-Aug,29-Aug,30-Aug,31-Aug,Totals,Sum,IsSum_Total_Same?,elev_meters_x,LATITUDE_IB_CW,LATITUDE_OB_CCW,LONGITUDE_IB_CW,LONGITUDE_OB_CCW,TOTAL_MINUTES,elev_meters_y
count,68928.000000,68928.000000,44940.000000,43296.000000,42824.000000,45244.000000,43892.000000,41799.000000,68928.000000,68928.000000,68928.000000,68928.000000,68928.000000,68928.000000,68928.000000,68928.000000,68928.000000,68928.000000
mean,29.789489,-95.360739,0.835651,7.542662,15.922065,3.138468,0.092269,0.000463,29.737328,22.152641,0.810338,18.623100,29.784479,29.784460,-95.386724,-95.386751,3039.842111,18.749361
std,0.157017,0.222964,0.493761,2.558003,2.565800,1.896357,0.528609,0.019700,13.215356,16.015701,0.392036,13.815052,0.141109,0.141168,0.178770,0.178812,1810.856936,12.374981
min,29.110000,-96.040000,0.000000,0.350000,2.340000,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.460000,29.078550,29.078550,-96.152700,-96.152700,-1.000000,-0.120000
25%,29.674494,-95.527994,0.480000,6.000000,14.360000,1.640000,0.000000,0.000000,28.640000,1.680000,1.000000,8.220000,29.683900,29.683800,-95.517700,-95.517600,1705.000000,10.300000
50%,29.782684,-95.349320,0.800000,7.360000,16.000000,2.640000,0.000000,0.000000,32.960000,30.040000,1.000000,15.740000,29.774300,29.774100,-95.381200,-95.381300,3315.000000,16.210000
75%,29.900000,-95.180000,1.080000,9.200000,17.560000,4.200000,0.000000,0.000000,38.200000,34.560000,1.000000,25.250000,29.883110,29.883110,-95.262200,-95.262400,4076.000000,23.040000
max,30.420000,-94.388900,3.620000,14.400000,27.360000,19.170000,5.420000,0.840000,56.000000,48.200000,1.000000,118.710000,30.421000,30.421000,-94.388372,-94.388372,9834.000000,108.650000

In [117]:
right_merge.to_csv("RF_Incidents_Merged.csv", index=False, header=True)